name: build xmrig

on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  macos-x64:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Make build dirs
      run: mkdir ${{github.workspace}}/build
    - name: configure deps
      run: brew install cmake libuv openssl hwloc
    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake .. -DOPENSSL_ROOT_DIR=$(brew --prefix openssl)
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make -j$(sysctl -n hw.logicalcpu)
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: xmrig
        path: ${{github.workspace}}/build/xmrig


