name: build xmrig

on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  macos:
    strategy:
      matrix:
        os:
          - macos-13
          - macos-14
        include:
          - os: macos-13
            output_archive: xmrig-macos-x64.tar
          - os: macos-14
            output_archive: xmrig-macos-arm64.tar
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Make build dirs
      run: mkdir ${{github.workspace}}/build
    - name: configure deps
      run: brew install cmake libuv openssl hwloc
    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake .. -DOPENSSL_ROOT_DIR=$(brew --prefix openssl)
    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make -j$(sysctl -n hw.logicalcpu)
    - name: archive artifacts
      working-directory: ${{github.workspace}}/build
      run: tar -cvf ${{ matrix.output_archive }} ${{github.workspace}}/build/xmrig
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.output_archive }}
        path: ${{github.workspace}}/build/xmrig*.tar


